### ISSUE TITLE
Unexpected response from the database: 302

### ISSUE THREAD

**Issue by notedit** [watson/airharvest#1]
/usr/local/lib/node_modules/airharvest/index.js:83
    if (err) throw err;
                   ^
Error: Unexpected response from the database: 302
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/airharvest/index.js:49:21)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming](http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:121:23)
    at Socket.socketOnData [as ondata](http.js:1583:20)
    at TCP.onread (net.js:525:27)

**Comment by watson** [comment]
Yeah, I think the database used to collect the data is no longer online 😞 I havne't gotten around to finding out why yet
